language: python
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION=1.8.11
  - DJANGO_VERSION>=1.9.4
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - python setup.py test
